### ISSUE TITLE
Write pseudocode for the extinguisher

### ISSUE THREAD

**Issue by omn0mn0m** [GW-Robotics/2017-Fire-Fighter#10]
Checklist of Functions
- [x] Run pump
- [x] Spray
- [x] Actuate valve

**Comment by omn0mn0m** [comment]
Jeremey is doing this...

**Comment by jwalrusisawesome** [comment]
Always on:  Air/water pump

if fire detected by fire sensors
    turn to fire
    activate versa valve 
    rotate servos so that the fire is adequately extinguished
    turn off versa valve
