### ISSUE TITLE
Get Micro Contact Limit Switches working

### ISSUE THREAD

**Issue by omn0mn0m** [GW-Robotics/2017-Fire-Fighter#18]

**Comment by Adrian-Haber** [comment]
Are these only being used on the linear motion system? Also do we want these as NO or NC switches.

**Comment by omn0mn0m** [comment]
@Adrian-Haber No idea, doesn't matter too much. For now just write code for both NO and NC, with the a variable we can set in the contructor for which one it is. Then in a function "is Active" that returns if it is low or high.

**Comment by omn0mn0m** [comment]
*constructor
