### ISSUE TITLE
Write pseudocode for the baby grabber

### ISSUE THREAD

**Issue by omn0mn0m** [GW-Robotics/2017-Fire-Fighter#9]
Checklist of Functions
- [x] Detect if aligned
- [x] Extend grabber
- [x] Retract grabber

**Comment by omn0mn0m** [comment]
Daniel is doing this

**Comment by danielvxn** [comment]
[pseudocode for baby grabber.py.docx](https://github.com/GW-Robotics/2017-Fire-Fighter/files/706359/pseudocode.for.baby.grabber.py.docx)

**Comment by omn0mn0m** [comment]
What happens if the robot finds red?

**Comment by omn0mn0m** [comment]
Pseudocode for red is the same as other colors, but looking for a red boolean from the vision software.
